//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Modules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Modules.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog operation is active, which is not permitted. This will be turned off..
        /// </summary>
        internal static string AnalogOperationWillBeDIsabled {
            get {
                return ResourceManager.GetString("AnalogOperationWillBeDIsabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consist address (CV19) is {0}. If not intentional, is recommended to reset this to zero..
        /// </summary>
        internal static string CV19Warning {
            get {
                return ResourceManager.GetString("CV19Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deacceleration is {0} which might be to high. If loco is to be used by other participants, this value will be adjusted..
        /// </summary>
        internal static string DeaccelerationWarning {
            get {
                return ResourceManager.GetString("DeaccelerationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder manufacturer: {0}.
        /// </summary>
        internal static string DecoderManufacturer {
            get {
                return ResourceManager.GetString("DecoderManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder number (CV16) is {0}. This will be used when writing to the decoder..
        /// </summary>
        internal static string DecoderNumberIsNonZero {
            get {
                return ResourceManager.GetString("DecoderNumberIsNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loco address {0} is already booked by {1} for loco {2}. Is this your loco? If not, you must enter a new address..
        /// </summary>
        internal static string ExistingLocoAddressWarning {
            get {
                return ResourceManager.GetString("ExistingLocoAddressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long address {0}.
        /// </summary>
        internal static string LongAddress {
            get {
                return ResourceManager.GetString("LongAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RailCom® is enabled. This is not permitted and will be disabled..
        /// </summary>
        internal static string RailComWillBeDisabled {
            get {
                return ResourceManager.GetString("RailComWillBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short address {0}.
        /// </summary>
        internal static string ShortAddress {
            get {
                return ResourceManager.GetString("ShortAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed steps is {0}.
        /// </summary>
        internal static string SpeedSteps {
            get {
                return ResourceManager.GetString("SpeedSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        internal static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
